apiVersion: v1
kind: Namespace
metadata:
  name: namespace-1
  labels:
    namespace: namespace-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "New change"
  name: busybox
  namespace: namespace-1
  labels:
    app: busybox
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        # command: ["tail -f /dev/null"]
        command: ["sleep", "60m"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: busybox
  namespace: namespace-1
  labels:
    app: busybox
spec:
  type: ClusterIP
  selector:
    app: busybox
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "New change"
  name: nginx
  namespace: namespace-1
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: namespace-1
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---