apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enable-namespace-1-pod-communitacion
  namespace: namespace-1
spec:
  podSelector:
    matchLabels:
      namespace: namespace-1
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            namespace: namespace-1
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enable-namespace-2-pod-communitacion
  namespace: namespace-2
spec:
  podSelector:
    matchLabels:
      namespace: namespace-2
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            namespace: namespace-2
      ports:
        - protocol: TCP
          port: 8080