apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: minimal
  components:
    pilot:
      k8s:
        resources:
          requests:
            memory: 1024Mi
