---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-pv1
  namespace: devops-apps
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv1