apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-countdown
spec:
  completions: 10
  parallelism: 3
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: parallel-counter
        image: ubuntu
        command:
         - "bin/bash"
         - "-c"
         - "for i in {0..15} ; do echo $i ; sleep 1; done"
      restartPolicy: Never